version: '3'
services:
  indexcards:
    container_name: indexcards
    image: indexcards:latest
    restart: always
    ports:
        - 3000:3000
    volumes:
      - /www/tabroom/api/config/config.js:/api/config/config.js:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
